// Copyright 2015 Silicon Laboratories, Inc.
//
//

// This file contains direct values from the user interface
// Enclosing macro to prevent multiple inclusion
#ifndef __SLAB_RADIO_USER_INPUT__
#define __SLAB_RADIO_USER_INPUT__


// Input options from user
// BASE_FREQUENCY = 915000000
#define RADIO_USER_INPUT_BASE_FREQUENCY 915000000
// BIT_ORDER = false
#define RADIO_USER_INPUT_BIT_ORDER FALSE
// CENTER_FREQUENCY = 915000000
#define RADIO_USER_INPUT_CENTER_FREQUENCY 915000000
// CHANNEL_NUMBER = 0
#define RADIO_USER_INPUT_CHANNEL_NUMBER 0
// CHANNEL_SPACING = 250000
#define RADIO_USER_INPUT_CHANNEL_SPACING 250000
// CHECK_CRC[0] = false
#define RADIO_USER_INPUT_CHECK_CRC[0] FALSE
// CHECK_CRC[1] = true
#define RADIO_USER_INPUT_CHECK_CRC[1] TRUE
// CHECK_CRC[2] = false
#define RADIO_USER_INPUT_CHECK_CRC[2] FALSE
// CHECK_CRC[3] = false
#define RADIO_USER_INPUT_CHECK_CRC[3] FALSE
// CHECK_CRC[4] = false
#define RADIO_USER_INPUT_CHECK_CRC[4] FALSE
// CHIP_HW_INTERRUPT = 32
#define RADIO_USER_INPUT_CHIP_HW_INTERRUPT 32
// CRC_PADDING = false
#define RADIO_USER_INPUT_CRC_PADDING FALSE
// CRC_START = true
#define RADIO_USER_INPUT_CRC_START TRUE
// CRYSTAL_CAP_BANK = 69
#define RADIO_USER_INPUT_CRYSTAL_CAP_BANK 69
// CRYSTAL_FREQUENCY = 30000000
#define RADIO_USER_INPUT_CRYSTAL_FREQUENCY 30000000
// CRYSTAL_TOLERANCE_RX = 20
#define RADIO_USER_INPUT_CRYSTAL_TOLERANCE_RX 20
// CRYSTAL_TOLERANCE_TX = 20
#define RADIO_USER_INPUT_CRYSTAL_TOLERANCE_TX 20
// CRYSTAL_USE_EXTERNAL_SOURCE = false
#define RADIO_USER_INPUT_CRYSTAL_USE_EXTERNAL_SOURCE FALSE
// DRIVE_STRENGTH = 0
#define RADIO_USER_INPUT_DRIVE_STRENGTH 0
// ENABLE_CHIP_HW_INTERRUPT = true
#define RADIO_USER_INPUT_ENABLE_CHIP_HW_INTERRUPT TRUE
// ENABLE_CRC[0] = false
#define RADIO_USER_INPUT_ENABLE_CRC[0] FALSE
// ENABLE_CRC[1] = true
#define RADIO_USER_INPUT_ENABLE_CRC[1] TRUE
// ENABLE_CRC[2] = false
#define RADIO_USER_INPUT_ENABLE_CRC[2] FALSE
// ENABLE_CRC[3] = false
#define RADIO_USER_INPUT_ENABLE_CRC[3] FALSE
// ENABLE_CRC[4] = false
#define RADIO_USER_INPUT_ENABLE_CRC[4] FALSE
// ENABLE_MODEM_HW_INTERRUPT = true
#define RADIO_USER_INPUT_ENABLE_MODEM_HW_INTERRUPT TRUE
// ENABLE_PACKET_HANDELR_HW_INTERRUPT = true
#define RADIO_USER_INPUT_ENABLE_PACKET_HANDELR_HW_INTERRUPT TRUE
// FLD_CRC_BITORDER = 0
#define RADIO_USER_INPUT_FLD_CRC_BITORDER 0
// FLD_CRC_ENDIAN = 0
#define RADIO_USER_INPUT_FLD_CRC_ENDIAN 0
// FLD_INVERT_CRC = false
#define RADIO_USER_INPUT_FLD_INVERT_CRC FALSE
// FLD_MANCHESTER_PATTERN = 0
#define RADIO_USER_INPUT_FLD_MANCHESTER_PATTERN 0
// FLD_MODEM_4GFSK_MODE = false
#define RADIO_USER_INPUT_FLD_MODEM_4GFSK_MODE FALSE
// FRR_CTL_A_MODE = 1
#define RADIO_USER_INPUT_FRR_CTL_A_MODE 1
// FRR_CTL_B_MODE = 2
#define RADIO_USER_INPUT_FRR_CTL_B_MODE 2
// FRR_CTL_C_MODE = 9
#define RADIO_USER_INPUT_FRR_CTL_C_MODE 9
// FRR_CTL_D_MODE = 0
#define RADIO_USER_INPUT_FRR_CTL_D_MODE 0
// GPIO0 = 3
#define RADIO_USER_INPUT_GPIO0 3
// GPIO0_PULLUP = false
#define RADIO_USER_INPUT_GPIO0_PULLUP FALSE
// GPIO1 = 2
#define RADIO_USER_INPUT_GPIO1 2
// GPIO1_PULLUP = false
#define RADIO_USER_INPUT_GPIO1_PULLUP FALSE
// GPIO2 = 32
#define RADIO_USER_INPUT_GPIO2 32
// GPIO2_PULLUP = false
#define RADIO_USER_INPUT_GPIO2_PULLUP FALSE
// GPIO3 = 33
#define RADIO_USER_INPUT_GPIO3 33
// GPIO3_PULLUP = false
#define RADIO_USER_INPUT_GPIO3_PULLUP FALSE
// HOP_ENABLE = 0
#define RADIO_USER_INPUT_HOP_ENABLE 0
// HOP_PREAMBLE_TIMEOUT = 20
#define RADIO_USER_INPUT_HOP_PREAMBLE_TIMEOUT 20
// HOP_RSSI_TIMEOUT = 10
#define RADIO_USER_INPUT_HOP_RSSI_TIMEOUT 10
// HOP_TABLE = 
#define RADIO_USER_INPUT_HOP_TABLE 
// HOP_TYPE = MANUAL_FREQUENCY_HOP
#define RADIO_USER_INPUT_HOP_TYPE MANUAL_FREQUENCY_HOP
// LDC_RX_TIME_ADJUST = 0
#define RADIO_USER_INPUT_LDC_RX_TIME_ADJUST 0
// LDC_SLEEP_TIME_ADJUST = 0
#define RADIO_USER_INPUT_LDC_SLEEP_TIME_ADJUST 0
// LDC_STEP_SIZE_ADJUST = 0
#define RADIO_USER_INPUT_LDC_STEP_SIZE_ADJUST 0
// LENGTH_SUB = 0
#define RADIO_USER_INPUT_LENGTH_SUB 0
// MATCH_BYTES = 0
#define RADIO_USER_INPUT_MATCH_BYTES 0
// MATCH_LOGIC[1] = AND
#define RADIO_USER_INPUT_MATCH_LOGIC[1] AND
// MATCH_LOGIC[2] = AND
#define RADIO_USER_INPUT_MATCH_LOGIC[2] AND
// MATCH_LOGIC[3] = AND
#define RADIO_USER_INPUT_MATCH_LOGIC[3] AND
// MATCH_MASK[0] = 00
#define RADIO_USER_INPUT_MATCH_MASK[0] 00
// MATCH_MASK[1] = 00
#define RADIO_USER_INPUT_MATCH_MASK[1] 00
// MATCH_MASK[2] = 00
#define RADIO_USER_INPUT_MATCH_MASK[2] 00
// MATCH_MASK[3] = 00
#define RADIO_USER_INPUT_MATCH_MASK[3] 00
// MATCH_OFFSET[0] = 0
#define RADIO_USER_INPUT_MATCH_OFFSET[0] 0
// MATCH_OFFSET[1] = 0
#define RADIO_USER_INPUT_MATCH_OFFSET[1] 0
// MATCH_OFFSET[2] = 0
#define RADIO_USER_INPUT_MATCH_OFFSET[2] 0
// MATCH_OFFSET[3] = 0
#define RADIO_USER_INPUT_MATCH_OFFSET[3] 0
// MATCH_POLARITY[0] = MATCH
#define RADIO_USER_INPUT_MATCH_POLARITY[0] MATCH
// MATCH_POLARITY[1] = MATCH
#define RADIO_USER_INPUT_MATCH_POLARITY[1] MATCH
// MATCH_POLARITY[2] = MATCH
#define RADIO_USER_INPUT_MATCH_POLARITY[2] MATCH
// MATCH_POLARITY[3] = MATCH
#define RADIO_USER_INPUT_MATCH_POLARITY[3] MATCH
// MATCH_VALUE[0] = 00
#define RADIO_USER_INPUT_MATCH_VALUE[0] 00
// MATCH_VALUE[1] = 00
#define RADIO_USER_INPUT_MATCH_VALUE[1] 00
// MATCH_VALUE[2] = 00
#define RADIO_USER_INPUT_MATCH_VALUE[2] 00
// MATCH_VALUE[3] = 00
#define RADIO_USER_INPUT_MATCH_VALUE[3] 00
// MODEM_HW_INTERRUPT = 6
#define RADIO_USER_INPUT_MODEM_HW_INTERRUPT 6
// NIRQ = 0
#define RADIO_USER_INPUT_NIRQ 0
// NIRQ_PULLUP = false
#define RADIO_USER_INPUT_NIRQ_PULLUP FALSE
// PACKET_HANDELR_HW_INTERRUPT = 59
#define RADIO_USER_INPUT_PACKET_HANDELR_HW_INTERRUPT 59
// PH_FIELD_SPLIT = true
#define RADIO_USER_INPUT_PH_FIELD_SPLIT TRUE
// PKT_ALLOW_BIT_ERR = 0
#define RADIO_USER_INPUT_PKT_ALLOW_BIT_ERR 0
// PKT_CRC_POLY = 4
#define RADIO_USER_INPUT_PKT_CRC_POLY 4
// PKT_CRC_SEED = 0
#define RADIO_USER_INPUT_PKT_CRC_SEED 0
// PKT_DATA_WHITENING_SEED = FF FF
#define RADIO_USER_INPUT_PKT_DATA_WHITENING_SEED FF FF
// PKT_ENABLE_PREAMBLE = true
#define RADIO_USER_INPUT_PKT_ENABLE_PREAMBLE TRUE
// PKT_FIELD_4GFSK[0] = false
#define RADIO_USER_INPUT_PKT_FIELD_4GFSK[0] FALSE
// PKT_FIELD_4GFSK[1] = false
#define RADIO_USER_INPUT_PKT_FIELD_4GFSK[1] FALSE
// PKT_FIELD_4GFSK[2] = false
#define RADIO_USER_INPUT_PKT_FIELD_4GFSK[2] FALSE
// PKT_FIELD_4GFSK[3] = false
#define RADIO_USER_INPUT_PKT_FIELD_4GFSK[3] FALSE
// PKT_FIELD_4GFSK[4] = false
#define RADIO_USER_INPUT_PKT_FIELD_4GFSK[4] FALSE
// PKT_FIELD_CONTAINING_LENGTH = 1
#define RADIO_USER_INPUT_PKT_FIELD_CONTAINING_LENGTH 1
// PKT_FIELD_LENGTH[0] = 1
#define RADIO_USER_INPUT_PKT_FIELD_LENGTH[0] 1
// PKT_FIELD_LENGTH[1] = 255
#define RADIO_USER_INPUT_PKT_FIELD_LENGTH[1] 255
// PKT_FIELD_LENGTH[2] = 0
#define RADIO_USER_INPUT_PKT_FIELD_LENGTH[2] 0
// PKT_FIELD_LENGTH[3] = 0
#define RADIO_USER_INPUT_PKT_FIELD_LENGTH[3] 0
// PKT_FIELD_LENGTH[4] = 0
#define RADIO_USER_INPUT_PKT_FIELD_LENGTH[4] 0
// PKT_FIELD_MANCHESTER[0] = false
#define RADIO_USER_INPUT_PKT_FIELD_MANCHESTER[0] FALSE
// PKT_FIELD_MANCHESTER[1] = false
#define RADIO_USER_INPUT_PKT_FIELD_MANCHESTER[1] FALSE
// PKT_FIELD_MANCHESTER[2] = false
#define RADIO_USER_INPUT_PKT_FIELD_MANCHESTER[2] FALSE
// PKT_FIELD_MANCHESTER[3] = false
#define RADIO_USER_INPUT_PKT_FIELD_MANCHESTER[3] FALSE
// PKT_FIELD_MANCHESTER[4] = false
#define RADIO_USER_INPUT_PKT_FIELD_MANCHESTER[4] FALSE
// PKT_FIELD_WHITEN[0] = false
#define RADIO_USER_INPUT_PKT_FIELD_WHITEN[0] FALSE
// PKT_FIELD_WHITEN[1] = false
#define RADIO_USER_INPUT_PKT_FIELD_WHITEN[1] FALSE
// PKT_FIELD_WHITEN[2] = false
#define RADIO_USER_INPUT_PKT_FIELD_WHITEN[2] FALSE
// PKT_FIELD_WHITEN[3] = false
#define RADIO_USER_INPUT_PKT_FIELD_WHITEN[3] FALSE
// PKT_FIELD_WHITEN[4] = false
#define RADIO_USER_INPUT_PKT_FIELD_WHITEN[4] FALSE
// PKT_LENGTH_ADJUST = 0
#define RADIO_USER_INPUT_PKT_LENGTH_ADJUST 0
// PKT_LENGTH_SIZE = 1
#define RADIO_USER_INPUT_PKT_LENGTH_SIZE 1
// PKT_LEN_ADD_TO_RX_FIFO = true
#define RADIO_USER_INPUT_PKT_LEN_ADD_TO_RX_FIFO TRUE
// PKT_LEN_IN_MSB = true
#define RADIO_USER_INPUT_PKT_LEN_IN_MSB TRUE
// PKT_NUMBER_OF_FIELDS = 2
#define RADIO_USER_INPUT_PKT_NUMBER_OF_FIELDS 2
// PKT_NUMBER_OF_RX_FIELDS = 2
#define RADIO_USER_INPUT_PKT_NUMBER_OF_RX_FIELDS 2
// PKT_PREAMBLE_EXTENDED_TIMEOUT = 0
#define RADIO_USER_INPUT_PKT_PREAMBLE_EXTENDED_TIMEOUT 0
// PKT_PREAMBLE_MANCHESTER_CONSTANT = false
#define RADIO_USER_INPUT_PKT_PREAMBLE_MANCHESTER_CONSTANT FALSE
// PKT_PREAMBLE_MANCHESTER_ENABLED = false
#define RADIO_USER_INPUT_PKT_PREAMBLE_MANCHESTER_ENABLED FALSE
// PKT_PREAMBLE_NONE_STANDARD = 00 00 00 00
#define RADIO_USER_INPUT_PKT_PREAMBLE_NONE_STANDARD 00 00 00 00
// PKT_PREAMBLE_PATTERN = 1
#define RADIO_USER_INPUT_PKT_PREAMBLE_PATTERN 1
// PKT_PREAMBLE_PATTERN_LENGTH = 0
#define RADIO_USER_INPUT_PKT_PREAMBLE_PATTERN_LENGTH 0
// PKT_PREAMBLE_RX_BIT_ERROR = 0
#define RADIO_USER_INPUT_PKT_PREAMBLE_RX_BIT_ERROR 0
// PKT_PREAMBLE_RX_THRESHOLD = 20
#define RADIO_USER_INPUT_PKT_PREAMBLE_RX_THRESHOLD 20
// PKT_PREAMBLE_TIMEOUT = 15
#define RADIO_USER_INPUT_PKT_PREAMBLE_TIMEOUT 15
// PKT_PREAMBLE_TX_LENGTH = 8
#define RADIO_USER_INPUT_PKT_PREAMBLE_TX_LENGTH 8
// PKT_RESET_DATAWHITENING = false
#define RADIO_USER_INPUT_PKT_RESET_DATAWHITENING FALSE
// PKT_RX_FIELD_4GFSK[0] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_4GFSK[0] FALSE
// PKT_RX_FIELD_4GFSK[1] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_4GFSK[1] FALSE
// PKT_RX_FIELD_4GFSK[2] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_4GFSK[2] FALSE
// PKT_RX_FIELD_4GFSK[3] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_4GFSK[3] FALSE
// PKT_RX_FIELD_4GFSK[4] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_4GFSK[4] FALSE
// PKT_RX_FIELD_LENGTH[0] = 1
#define RADIO_USER_INPUT_PKT_RX_FIELD_LENGTH[0] 1
// PKT_RX_FIELD_LENGTH[1] = 255
#define RADIO_USER_INPUT_PKT_RX_FIELD_LENGTH[1] 255
// PKT_RX_FIELD_LENGTH[2] = 0
#define RADIO_USER_INPUT_PKT_RX_FIELD_LENGTH[2] 0
// PKT_RX_FIELD_LENGTH[3] = 0
#define RADIO_USER_INPUT_PKT_RX_FIELD_LENGTH[3] 0
// PKT_RX_FIELD_LENGTH[4] = 0
#define RADIO_USER_INPUT_PKT_RX_FIELD_LENGTH[4] 0
// PKT_RX_FIELD_MANCHESTER[0] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_MANCHESTER[0] FALSE
// PKT_RX_FIELD_MANCHESTER[1] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_MANCHESTER[1] FALSE
// PKT_RX_FIELD_MANCHESTER[2] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_MANCHESTER[2] FALSE
// PKT_RX_FIELD_MANCHESTER[3] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_MANCHESTER[3] FALSE
// PKT_RX_FIELD_MANCHESTER[4] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_MANCHESTER[4] FALSE
// PKT_RX_FIELD_WHITEN[0] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_WHITEN[0] FALSE
// PKT_RX_FIELD_WHITEN[1] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_WHITEN[1] FALSE
// PKT_RX_FIELD_WHITEN[2] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_WHITEN[2] FALSE
// PKT_RX_FIELD_WHITEN[3] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_WHITEN[3] FALSE
// PKT_RX_FIELD_WHITEN[4] = false
#define RADIO_USER_INPUT_PKT_RX_FIELD_WHITEN[4] FALSE
// PKT_RX_THRESHOLD = 48
#define RADIO_USER_INPUT_PKT_RX_THRESHOLD 48
// PKT_SKIP_SYNCWORD = false
#define RADIO_USER_INPUT_PKT_SKIP_SYNCWORD FALSE
// PKT_SKIP_SYNC_TIMEOUT = false
#define RADIO_USER_INPUT_PKT_SKIP_SYNC_TIMEOUT FALSE
// PKT_SYNC_4GFSK = false
#define RADIO_USER_INPUT_PKT_SYNC_4GFSK FALSE
// PKT_SYNC_LENGTH = 2
#define RADIO_USER_INPUT_PKT_SYNC_LENGTH 2
// PKT_SYNC_MANCHESTER = false
#define RADIO_USER_INPUT_PKT_SYNC_MANCHESTER FALSE
// PKT_SYNC_WORD = 2D D4
#define RADIO_USER_INPUT_PKT_SYNC_WORD 2D D4
// PKT_SYNC_WORD_API = B4 2B
#define RADIO_USER_INPUT_PKT_SYNC_WORD_API B4 2B
// PKT_TX_THRESHOLD = 48
#define RADIO_USER_INPUT_PKT_TX_THRESHOLD 48
// PKT_VARIABLE_LENGTH_FIELD = 2
#define RADIO_USER_INPUT_PKT_VARIABLE_LENGTH_FIELD 2
// PKT_VARIABLE_PACKET_LENGTH_ENABLE = true
#define RADIO_USER_INPUT_PKT_VARIABLE_PACKET_LENGTH_ENABLE TRUE
// PKT_WHITENING_POLY = 1280
#define RADIO_USER_INPUT_PKT_WHITENING_POLY 1280
// PN_DIRECTION = 1
#define RADIO_USER_INPUT_PN_DIRECTION 1
// POWER_ENABLE_RAMP_CONTROL = false
#define RADIO_USER_INPUT_POWER_ENABLE_RAMP_CONTROL FALSE
// POWER_PA_BIAS = 12
#define RADIO_USER_INPUT_POWER_PA_BIAS 12
// POWER_PA_MODE = 0
#define RADIO_USER_INPUT_POWER_PA_MODE 0
// POWER_PA_POWERLEVEL = 127
#define RADIO_USER_INPUT_POWER_PA_POWERLEVEL 127
// POWER_RAMPING_TIME = 14
#define RADIO_USER_INPUT_POWER_RAMPING_TIME 14
// POWER_RAMP_HV = 29
#define RADIO_USER_INPUT_POWER_RAMP_HV 29
// POWER_REGULATOR_VOLTAGE = 15
#define RADIO_USER_INPUT_POWER_REGULATOR_VOLTAGE 15
// RFPARAM_4GFSK_MAP = 0
#define RADIO_USER_INPUT_RFPARAM_4GFSK_MAP 0
// RFPARAM_ADAPTIVE_CHFILL = false
#define RADIO_USER_INPUT_RFPARAM_ADAPTIVE_CHFILL FALSE
// RFPARAM_BANDWIDTH_TIME = 50
#define RADIO_USER_INPUT_RFPARAM_BANDWIDTH_TIME 50
// RFPARAM_BER_MODE = false
#define RADIO_USER_INPUT_RFPARAM_BER_MODE FALSE
// RFPARAM_CHECKTHRESHOLDATLATCH = false
#define RADIO_USER_INPUT_RFPARAM_CHECKTHRESHOLDATLATCH FALSE
// RFPARAM_DATA_RATE = 64000
#define RADIO_USER_INPUT_RFPARAM_DATA_RATE 64000
// RFPARAM_DEVIATION = 96000
#define RADIO_USER_INPUT_RFPARAM_DEVIATION 96000
// RFPARAM_DEVIATION_ERROR_NEGATIVE = 0
#define RADIO_USER_INPUT_RFPARAM_DEVIATION_ERROR_NEGATIVE 0
// RFPARAM_DEVIATION_ERROR_POSITIVE = 0
#define RADIO_USER_INPUT_RFPARAM_DEVIATION_ERROR_POSITIVE 0
// RFPARAM_ENABLEANTENNADIVERSITY = false
#define RADIO_USER_INPUT_RFPARAM_ENABLEANTENNADIVERSITY FALSE
// RFPARAM_ENABLEIQCALIBRATION = false
#define RADIO_USER_INPUT_RFPARAM_ENABLEIQCALIBRATION FALSE
// RFPARAM_ENABLE_HIGH_PERFORMANCE_CHANNEL_FILLTER = true
#define RADIO_USER_INPUT_RFPARAM_ENABLE_HIGH_PERFORMANCE_CHANNEL_FILLTER TRUE
// RFPARAM_ENABLE_MANUAL_RXBANDWIDTH = false
#define RADIO_USER_INPUT_RFPARAM_ENABLE_MANUAL_RXBANDWIDTH FALSE
// RFPARAM_ENABLE_PLL_AFC = false
#define RADIO_USER_INPUT_RFPARAM_ENABLE_PLL_AFC FALSE
// RFPARAM_IF_MODE = 2
#define RADIO_USER_INPUT_RFPARAM_IF_MODE 2
// RFPARAM_MODULATION_MODE = PACKET
#define RADIO_USER_INPUT_RFPARAM_MODULATION_MODE PACKET
// RFPARAM_MODULATION_TYPE = GFSK2
#define RADIO_USER_INPUT_RFPARAM_MODULATION_TYPE GFSK2
// RFPARAM_OSR_TUNE = 0
#define RADIO_USER_INPUT_RFPARAM_OSR_TUNE 0
// RFPARAM_PREAMBLE_PATTERN = 0
#define RADIO_USER_INPUT_RFPARAM_PREAMBLE_PATTERN 0
// RFPARAM_RSSI_AVERAGE = 2
#define RADIO_USER_INPUT_RFPARAM_RSSI_AVERAGE 2
// RFPARAM_RSSI_JUMP_THRESHOLD = 12
#define RADIO_USER_INPUT_RFPARAM_RSSI_JUMP_THRESHOLD 12
// RFPARAM_RSSI_LATCH = 0
#define RADIO_USER_INPUT_RFPARAM_RSSI_LATCH 0
// RFPARAM_RSSI_THRESHOLD = 255
#define RADIO_USER_INPUT_RFPARAM_RSSI_THRESHOLD 255
// RFPARAM_RXBANDWIDTH = 150000
#define RADIO_USER_INPUT_RFPARAM_RXBANDWIDTH 150000
// RFPARAM_RXDATARATEERROR = 0
#define RADIO_USER_INPUT_RFPARAM_RXDATARATEERROR 0
// RFPARAM_RX_CURRENT = 0
#define RADIO_USER_INPUT_RFPARAM_RX_CURRENT 0
// RFPARAM_RX_PERFORMANCE = 0
#define RADIO_USER_INPUT_RFPARAM_RX_PERFORMANCE 0
// RX_CHECK_CRC[0] = false
#define RADIO_USER_INPUT_RX_CHECK_CRC[0] FALSE
// RX_CHECK_CRC[1] = false
#define RADIO_USER_INPUT_RX_CHECK_CRC[1] FALSE
// RX_CHECK_CRC[2] = false
#define RADIO_USER_INPUT_RX_CHECK_CRC[2] FALSE
// RX_CHECK_CRC[3] = false
#define RADIO_USER_INPUT_RX_CHECK_CRC[3] FALSE
// RX_CHECK_CRC[4] = false
#define RADIO_USER_INPUT_RX_CHECK_CRC[4] FALSE
// RX_CRC_START = true
#define RADIO_USER_INPUT_RX_CRC_START TRUE
// RX_ENABLE_CRC[0] = false
#define RADIO_USER_INPUT_RX_ENABLE_CRC[0] FALSE
// RX_ENABLE_CRC[1] = false
#define RADIO_USER_INPUT_RX_ENABLE_CRC[1] FALSE
// RX_ENABLE_CRC[2] = false
#define RADIO_USER_INPUT_RX_ENABLE_CRC[2] FALSE
// RX_ENABLE_CRC[3] = false
#define RADIO_USER_INPUT_RX_ENABLE_CRC[3] FALSE
// RX_ENABLE_CRC[4] = false
#define RADIO_USER_INPUT_RX_ENABLE_CRC[4] FALSE
// SDO = 0
#define RADIO_USER_INPUT_SDO 0
// SDO_PULLUP = false
#define RADIO_USER_INPUT_SDO_PULLUP FALSE
// SELECTED_CHIP = si4463~revC2A
#define RADIO_USER_INPUT_SELECTED_CHIP si4463~revC2A
// SW_CRC_CTRL = false
#define RADIO_USER_INPUT_SW_CRC_CTRL FALSE
// SW_WHT_CTRL = false
#define RADIO_USER_INPUT_SW_WHT_CTRL FALSE
// SYNC_ERROR_ONLY_BEGIN = 0
#define RADIO_USER_INPUT_SYNC_ERROR_ONLY_BEGIN 0
// SYSCLOCK_32KHZ_CLOCK = 0
#define RADIO_USER_INPUT_SYSCLOCK_32KHZ_CLOCK 0
// SYSCLOCK_CLOCK_OUTPUT = 0
#define RADIO_USER_INPUT_SYSCLOCK_CLOCK_OUTPUT 0
// SYSCLOCK_ENABLE_DIVIDED_CLOCK_OUTPUT = false
#define RADIO_USER_INPUT_SYSCLOCK_ENABLE_DIVIDED_CLOCK_OUTPUT FALSE
// TRANSMIT_CRC[0] = false
#define RADIO_USER_INPUT_TRANSMIT_CRC[0] FALSE
// TRANSMIT_CRC[1] = true
#define RADIO_USER_INPUT_TRANSMIT_CRC[1] TRUE
// TRANSMIT_CRC[2] = false
#define RADIO_USER_INPUT_TRANSMIT_CRC[2] FALSE
// TRANSMIT_CRC[3] = false
#define RADIO_USER_INPUT_TRANSMIT_CRC[3] FALSE
// TRANSMIT_CRC[4] = false
#define RADIO_USER_INPUT_TRANSMIT_CRC[4] FALSE
// WHT_BIT_NUM = 0
#define RADIO_USER_INPUT_WHT_BIT_NUM 0

// Input options for the chip configurator
// radio.profile = EZRadioSimplePacket
#define CHIP_CONFIG_INPUT_RADIO_PROFILE "EZRadioSimplePacket"
// Pkt.PKT_RX_FIELD_5_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_5_CONFIG__M_4FSK FALSE
// FastResponseRegs.FRR_CTL_D_MODE__FRR_D_MODE = 0
#define CHIP_CONFIG_INPUT_FASTRESPONSEREGS_FRR_CTL_D_MODE__FRR_D_MODE 0
// Pkt.PKT_RX_FIELD_2_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_2_CONFIG__MANCH FALSE
// Modem.API_freq_xo = 30000000
#define CHIP_CONFIG_INPUT_MODEM_API_FREQ_XO 30000000
// Pkt.PKT_FIELD_3_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_CRC_CONFIG__CRC_ENABLE FALSE
// GpioPinCfg.nirq_mode = 0
#define CHIP_CONFIG_INPUT_GPIOPINCFG_NIRQ_MODE 0
// Pkt.PKT_RX_FIELD_3_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_3_CONFIG__M_4FSK FALSE
// Pkt.PKT_CONFIG1__M_4FSK_EN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG1__M_4FSK_EN FALSE
// Pkt.PKT_FIELD_4_CRC_CONFIG__SEND_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_CRC_CONFIG__SEND_CRC FALSE
// Pkt.PKT_FIELD_4_LENGTH__FIELD_4_LENGTH = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_LENGTH__FIELD_4_LENGTH 0
// Pkt.PKT_FIELD_2_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_CONFIG__WHITEN FALSE
// GpioPinCfg.drv_strength = 0
#define CHIP_CONFIG_INPUT_GPIOPINCFG_DRV_STRENGTH 0
// Pkt.PKT_FIELD_2_CRC_CONFIG__CHECK_CRC = true
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_CRC_CONFIG__CHECK_CRC TRUE
// Pkt.PKT_FIELD_3_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_CONFIG__MANCH FALSE
// Pkt.PKT_FIELD_5_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_CONFIG__MANCH FALSE
// Pkt.PKT_WHT_BIT_NUM__SW_WHT_CTRL = false
#define CHIP_CONFIG_INPUT_PKT_PKT_WHT_BIT_NUM__SW_WHT_CTRL FALSE
// Pkt.PKT_RX_FIELD_3_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_3_CRC_CONFIG__CRC_ENABLE FALSE
// Pkt.PKT_FIELD_2_LENGTH__FIELD_2_LENGTH = 255
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_LENGTH__FIELD_2_LENGTH 255
// Sync.SYNC_CONFIG__RX_ERRORS = 0
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG__RX_ERRORS 0
// Pkt.PKT_FIELD_2_CRC_CONFIG__CRC_ENABLE = true
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_CRC_CONFIG__CRC_ENABLE TRUE
// Pkt.PKT_FIELD_5_LENGTH__FIELD_5_LENGTH = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_LENGTH__FIELD_5_LENGTH 0
// Modem.API_inputBW = false
#define CHIP_CONFIG_INPUT_MODEM_API_INPUTBW FALSE
// Pkt.PKT_CONFIG1__PH_FIELD_SPLIT = true
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG1__PH_FIELD_SPLIT TRUE
// Pkt.PKT_FIELD_5_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_CRC_CONFIG__CHECK_CRC FALSE
// Global.GLOBAL_CLK_CFG__DIVIDED_CLK_EN = false
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_CLK_CFG__DIVIDED_CLK_EN FALSE
// Pkt.PKT_FIELD_4_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_CONFIG__M_4FSK FALSE
// Preamble.PREAMBLE_CONFIG_NSTD__RX_ERRORS = 0
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG_NSTD__RX_ERRORS 0
// Pkt.PKT_FIELD_1_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CRC_CONFIG__CRC_ENABLE FALSE
// Modem.API_High_perf_Ch_Fil = true
#define CHIP_CONFIG_INPUT_MODEM_API_HIGH_PERF_CH_FIL TRUE
// Pkt.PKT_FIELD_3_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_CONFIG__WHITEN FALSE
// Preamble.PREAMBLE_CONFIG__MAN_ENABLE = false
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG__MAN_ENABLE FALSE
// Preamble.PREAMBLE_CONFIG_NSTD__PATTERN_LENGTH = 0
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG_NSTD__PATTERN_LENGTH 0
// Pkt.PKT_RX_FIELD_3_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_3_CONFIG__MANCH FALSE
// Preamble.PREAMBLE_CONFIG_STD_1__RX_THRESH = 20
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG_STD_1__RX_THRESH 20
// InterruptControl.INT_CTL_ENABLE__MODEM_INT_STATUS_EN = true
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_ENABLE__MODEM_INT_STATUS_EN TRUE
// Pkt.PKT_RX_FIELD_4_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_4_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_FIELD_1_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CONFIG__MANCH FALSE
// Global.GLOBAL_CLK_CFG__CLK_32K_SEL = 2
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_CLK_CFG__CLK_32K_SEL 2
// Pkt.PKT_RX_FIELD_4_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_4_CONFIG__M_4FSK FALSE
// Pkt.PKT_FIELD_1_CRC_CONFIG__CRC_START = true
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CRC_CONFIG__CRC_START TRUE
// Modem.API_ant_div = false
#define CHIP_CONFIG_INPUT_MODEM_API_ANT_DIV FALSE
// Pkt.PKT_RX_FIELD_5_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_5_CONFIG__MANCH FALSE
// Modem.API_Ch_Fil_Bw_AFC = false
#define CHIP_CONFIG_INPUT_MODEM_API_CH_FIL_BW_AFC FALSE
// Pkt.PKT_RX_FIELD_3_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_3_CONFIG__WHITEN FALSE
// Modem.API_fc = 915000000
#define CHIP_CONFIG_INPUT_MODEM_API_FC 915000000
// PowerAmplifier.PA_RAMP_EX__TC = 14
#define CHIP_CONFIG_INPUT_POWERAMPLIFIER_PA_RAMP_EX__TC 14
// InterruptControl.INT_CTL_ENABLE__CHIP_INT_STATUS_EN = true
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_ENABLE__CHIP_INT_STATUS_EN TRUE
// Pkt.PKT_FIELD_5_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_CONFIG__M_4FSK FALSE
// Pkt.PKT_FIELD_2_CRC_CONFIG__SEND_CRC = true
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_CRC_CONFIG__SEND_CRC TRUE
// Pkt.PKT_FIELD_2_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_CONFIG__MANCH FALSE
// Pkt.PKT_RX_FIELD_5_LENGTH__RX_FIELD_5_LENGTH = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_5_LENGTH__RX_FIELD_5_LENGTH 0
// Pkt.PKT_FIELD_3_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_CONFIG__M_4FSK FALSE
// Preamble.PREAMBLE_TX_LENGTH__TX_LENGTH = 8
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_TX_LENGTH__TX_LENGTH 8
// Pkt.PKT_RX_FIELD_1_LENGTH__RX_FIELD_1_LENGTH = 1
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_LENGTH__RX_FIELD_1_LENGTH 1
// Modem.API_Rsymb = 64000
#define CHIP_CONFIG_INPUT_MODEM_API_RSYMB 64000
// Pkt.PKT_RX_FIELD_1_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_CONFIG__WHITEN FALSE
// Pkt.PKT_RX_FIELD_5_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_5_CONFIG__WHITEN FALSE
// Pkt.PKT_RX_THRESHOLD__RX_THRESHOLD = 48
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_THRESHOLD__RX_THRESHOLD 48
// Pkt.PKT_FIELD_1_LENGTH__FIELD_1_LENGTH = 1
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_LENGTH__FIELD_1_LENGTH 1
// Pkt.PKT_FIELD_3_LENGTH__FIELD_3_LENGTH = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_LENGTH__FIELD_3_LENGTH 0
// Pkt.PKT_FIELD_2_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_2_CONFIG__M_4FSK FALSE
// Pkt.PKT_RX_FIELD_4_LENGTH__RX_FIELD_4_LENGTH = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_4_LENGTH__RX_FIELD_4_LENGTH 0
// Pkt.PKT_TX_THRESHOLD__TX_THRESHOLD = 48
#define CHIP_CONFIG_INPUT_PKT_PKT_TX_THRESHOLD__TX_THRESHOLD 48
// FastResponseRegs.FRR_CTL_C_MODE__FRR_C_MODE = 9
#define CHIP_CONFIG_INPUT_FASTRESPONSEREGS_FRR_CTL_C_MODE__FRR_C_MODE 9
// Pkt.PKT_RX_FIELD_3_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_3_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_RX_FIELD_4_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_4_CRC_CONFIG__CRC_ENABLE FALSE
// Pkt.PKT_FIELD_5_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_CONFIG__WHITEN FALSE
// Modem.API_Max_Rb_Error = 0
#define CHIP_CONFIG_INPUT_MODEM_API_MAX_RB_ERROR 0
// Pkt.PKT_FIELD_4_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_CONFIG__WHITEN FALSE
// Modem.API_OSRtune = 0
#define CHIP_CONFIG_INPUT_MODEM_API_OSRTUNE 0
// Pkt.PKT_RX_FIELD_2_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_2_CRC_CONFIG__CHECK_CRC FALSE
// InterruptControl.INT_CTL_ENABLE__PH_INT_STATUS_EN = true
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_ENABLE__PH_INT_STATUS_EN TRUE
// Modem.API_if_mode = 2
#define CHIP_CONFIG_INPUT_MODEM_API_IF_MODE 2
// Global.GLOBAL_CLK_CFG__DIVIDED_CLK_SEL = 0
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_CLK_CFG__DIVIDED_CLK_SEL 0
// Pkt.PKT_FIELD_1_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CONFIG__M_4FSK FALSE
// Pkt.PKT_RX_FIELD_2_LENGTH__RX_FIELD_2_LENGTH = 255
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_2_LENGTH__RX_FIELD_2_LENGTH 255
// Pkt.PKT_CONFIG1__BIT_ORDER = false
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG1__BIT_ORDER FALSE
// Pkt.PKT_RX_FIELD_2_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_2_CONFIG__WHITEN FALSE
// Pkt.PKT_RX_FIELD_1_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_CONFIG__M_4FSK FALSE
// Pkt.PKT_RX_FIELD_1_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_WHT_BIT_NUM__SW_CRC_CTRL = false
#define CHIP_CONFIG_INPUT_PKT_PKT_WHT_BIT_NUM__SW_CRC_CTRL FALSE
// Pkt.PKT_CONFIG1__MANCH_POL = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG1__MANCH_POL 0
// FastResponseRegs.FRR_CTL_B_MODE__FRR_B_MODE = 2
#define CHIP_CONFIG_INPUT_FASTRESPONSEREGS_FRR_CTL_B_MODE__FRR_B_MODE 2
// Pkt.PKT_RX_FIELD_2_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_2_CONFIG__M_4FSK FALSE
// Preamble.PREAMBLE_CONFIG__STANDARD_PREAM = 1
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG__STANDARD_PREAM 1
// Pkt.PKT_RX_FIELD_4_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_4_CONFIG__WHITEN FALSE
// Global.GLOBAL_WUT_R__WUT_R = 0
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_WUT_R__WUT_R 0
// Pkt.PKT_WHT_BIT_NUM__WHT_BIT_NUM = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_WHT_BIT_NUM__WHT_BIT_NUM 0
// Pkt.PKT_FIELD_1_CONFIG__WHITEN = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CONFIG__WHITEN FALSE
// Pkt.PKT_CRC_CONFIG__CRC_SEED = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_CRC_CONFIG__CRC_SEED 0
// Pkt.PKT_FIELD_4_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_CONFIG__MANCH FALSE
// Pkt.PKT_RX_FIELD_1_CRC_CONFIG__CRC_START = true
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_CRC_CONFIG__CRC_START TRUE
// CrystalCapBank.value = 69
#define CHIP_CONFIG_INPUT_CRYSTALCAPBANK_VALUE 69
// Pkt.PKT_WHT_POLY__WHT_POLY = 1280
#define CHIP_CONFIG_INPUT_PKT_PKT_WHT_POLY__WHT_POLY 1280
// FastResponseRegs.FRR_CTL_A_MODE__FRR_A_MODE = 1
#define CHIP_CONFIG_INPUT_FASTRESPONSEREGS_FRR_CTL_A_MODE__FRR_A_MODE 1
// Pkt.PKT_FIELD_3_CRC_CONFIG__SEND_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_CRC_CONFIG__SEND_CRC FALSE
// Pkt.PKT_CONFIG1__CRC_INVERT = false
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG1__CRC_INVERT FALSE
// Preamble.PREAMBLE_CONFIG_STD_1__SKIP_SYNC_TIMEOUT = false
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG_STD_1__SKIP_SYNC_TIMEOUT FALSE
// Modem.API_BER_mode = false
#define CHIP_CONFIG_INPUT_MODEM_API_BER_MODE FALSE
// Pkt.PKT_CRC_CONFIG__CRC_POLYNOMIAL = 4
#define CHIP_CONFIG_INPUT_PKT_PKT_CRC_CONFIG__CRC_POLYNOMIAL 4
// Pkt.PKT_FIELD_1_CRC_CONFIG__SEND_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CRC_CONFIG__SEND_CRC FALSE
// Pkt.PKT_RX_FIELD_5_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_5_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_FIELD_3_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_3_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_RX_FIELD_4_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_4_CONFIG__MANCH FALSE
// ModemFsk4Map.value = 0
#define CHIP_CONFIG_INPUT_MODEMFSK4MAP_VALUE 0
// PerformIqCal.value = false
#define CHIP_CONFIG_INPUT_PERFORMIQCAL_VALUE FALSE
// Pkt.PKT_RX_FIELD_5_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_5_CRC_CONFIG__CRC_ENABLE FALSE
// Global.GLOBAL_WUT_LDC__WUT_LDC = 0
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_WUT_LDC__WUT_LDC 0
// Pkt.PKT_FIELD_1_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_FIELD_5_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_CRC_CONFIG__CRC_ENABLE FALSE
// Preamble.PREAMBLE_CONFIG_STD_2__RX_PREAMBLE_TIMEOUT_EXTEND = 0
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG_STD_2__RX_PREAMBLE_TIMEOUT_EXTEND 0
// Modem.API_RXBW = 150000
#define CHIP_CONFIG_INPUT_MODEM_API_RXBW 150000
// Modem.API_Fdev = 96000
#define CHIP_CONFIG_INPUT_MODEM_API_FDEV 96000
// Pkt.PKT_RX_FIELD_1_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_CONFIG__MANCH FALSE
// Pkt.PKT_RX_FIELD_3_LENGTH__RX_FIELD_3_LENGTH = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_3_LENGTH__RX_FIELD_3_LENGTH 0
// GpioPinCfg.sdo_mode = 0
#define CHIP_CONFIG_INPUT_GPIOPINCFG_SDO_MODE 0
// Preamble.PREAMBLE_CONFIG_STD_2__RX_PREAMBLE_TIMEOUT = 15
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG_STD_2__RX_PREAMBLE_TIMEOUT 15
// Pkt.PKT_RX_FIELD_2_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_2_CRC_CONFIG__CRC_ENABLE FALSE
// Pkt.PKT_FIELD_1_CONFIG__PN_START = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_1_CONFIG__PN_START FALSE
// Sync.SYNC_CONFIG__MANCH = false
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG__MANCH FALSE
// Pkt.PKT_FIELD_4_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_CRC_CONFIG__CRC_ENABLE FALSE
// Global.GLOBAL_WUT_M__WUT_M = 0
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_WUT_M__WUT_M 0
// Preamble.PREAMBLE_CONFIG__MAN_CONST = false
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG__MAN_CONST FALSE
// Sync.SYNC_CONFIG__SKIP_TX = false
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG__SKIP_TX FALSE
// Sync.SYNC_CONFIG__M_4FSK = false
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG__M_4FSK FALSE
// Pkt.PKT_RX_FIELD_1_CRC_CONFIG__CRC_ENABLE = false
#define CHIP_CONFIG_INPUT_PKT_PKT_RX_FIELD_1_CRC_CONFIG__CRC_ENABLE FALSE
// Pkt.PKT_FIELD_4_CRC_CONFIG__CHECK_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_4_CRC_CONFIG__CHECK_CRC FALSE
// Pkt.PKT_FIELD_5_CRC_CONFIG__SEND_CRC = false
#define CHIP_CONFIG_INPUT_PKT_PKT_FIELD_5_CRC_CONFIG__SEND_CRC FALSE
// Pkt.PKT_CONFIG1__CRC_ENDIAN = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG1__CRC_ENDIAN 0
// Modem.API_crystal_tol = 20
#define CHIP_CONFIG_INPUT_MODEM_API_CRYSTAL_TOL 20
// GpioPinCfg.gpio_mode = [3, 2, 32, 33]
#define CHIP_CONFIG_INPUT_GPIOPINCFG_GPIO_MODE "[3, 2, 32, 33]"
// GpioPinCfg.gpio_pull_ctl = [0, 0, 0, 0]
#define CHIP_CONFIG_INPUT_GPIOPINCFG_GPIO_PULL_CTL "[0, 0, 0, 0]"
// InterruptControl.INT_CTL_PH_ENABLE__RX_FIFO_ALMOST_FULL_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__RX_FIFO_ALMOST_FULL_EN 1
// InterruptControl.INT_CTL_PH_ENABLE__TX_FIFO_ALMOST_EMPTY_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__TX_FIFO_ALMOST_EMPTY_EN 1
// InterruptControl.INT_CTL_PH_ENABLE__CRC_ERROR_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__CRC_ERROR_EN 1
// InterruptControl.INT_CTL_PH_ENABLE__PACKET_RX_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__PACKET_RX_EN 1
// InterruptControl.INT_CTL_PH_ENABLE__PACKET_SENT_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__PACKET_SENT_EN 1
// InterruptControl.INT_CTL_PH_ENABLE__FILTER_MISS_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__FILTER_MISS_EN 0
// InterruptControl.INT_CTL_PH_ENABLE__FILTER_MATCH_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_PH_ENABLE__FILTER_MATCH_EN 0
// InterruptControl.INT_CTL_MODEM_ENABLE__SYNC_DETECT_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__SYNC_DETECT_EN 0
// InterruptControl.INT_CTL_MODEM_ENABLE__PREAMBLE_DETECT_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__PREAMBLE_DETECT_EN 1
// InterruptControl.INT_CTL_MODEM_ENABLE__INVALID_PREAMBLE_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__INVALID_PREAMBLE_EN 1
// InterruptControl.INT_CTL_MODEM_ENABLE__RSSI_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__RSSI_EN 0
// InterruptControl.INT_CTL_MODEM_ENABLE__RSSI_JUMP_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__RSSI_JUMP_EN 0
// InterruptControl.INT_CTL_MODEM_ENABLE__INVALID_SYNC_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__INVALID_SYNC_EN 0
// InterruptControl.INT_CTL_MODEM_ENABLE__POSTAMBLE_DETECT_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__POSTAMBLE_DETECT_EN 0
// InterruptControl.INT_CTL_MODEM_ENABLE__RSSI_LATCH_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_MODEM_ENABLE__RSSI_LATCH_EN 0
// InterruptControl.INT_CTL_CHIP_ENABLE__WUT_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__WUT_EN 0
// InterruptControl.INT_CTL_CHIP_ENABLE__LOW_BATT_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__LOW_BATT_EN 0
// InterruptControl.INT_CTL_CHIP_ENABLE__CHIP_READY_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__CHIP_READY_EN 0
// InterruptControl.INT_CTL_CHIP_ENABLE__CMD_ERROR_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__CMD_ERROR_EN 0
// InterruptControl.INT_CTL_CHIP_ENABLE__STATE_CHANGE_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__STATE_CHANGE_EN 0
// InterruptControl.INT_CTL_CHIP_ENABLE__FIFO_UNDERFLOW_OVERFLOW_ERROR_EN = 1
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__FIFO_UNDERFLOW_OVERFLOW_ERROR_EN 1
// InterruptControl.INT_CTL_CHIP_ENABLE__CAL_EN = 0
#define CHIP_CONFIG_INPUT_INTERRUPTCONTROL_INT_CTL_CHIP_ENABLE__CAL_EN 0
// Preamble.PREAMBLE_CONFIG__LENGTH_CONFIG = 1
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_CONFIG__LENGTH_CONFIG 1
// Preamble.PREAMBLE_PATTERN__PATTERN = 0
#define CHIP_CONFIG_INPUT_PREAMBLE_PREAMBLE_PATTERN__PATTERN 0
// Modem.API_ETSI = 0
#define CHIP_CONFIG_INPUT_MODEM_API_ETSI 0
// Modem.Fdev_error = 0
#define CHIP_CONFIG_INPUT_MODEM_FDEV_ERROR 0
// Modem.API_afc_en = 0
#define CHIP_CONFIG_INPUT_MODEM_API_AFC_EN 0
// Modem.API_pm_pattern = 0
#define CHIP_CONFIG_INPUT_MODEM_API_PM_PATTERN 0
// Modem.API_dsa_mode = 0
#define CHIP_CONFIG_INPUT_MODEM_API_DSA_MODE 0
// Pkt.PKT_LEN__DST_FIELD = 2
#define CHIP_CONFIG_INPUT_PKT_PKT_LEN__DST_FIELD 2
// Pkt.PKT_LEN_FIELD_SOURCE__SRC_FIELD = 1
#define CHIP_CONFIG_INPUT_PKT_PKT_LEN_FIELD_SOURCE__SRC_FIELD 1
// Pkt.PKT_LEN__SIZE = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_LEN__SIZE 0
// Pkt.PKT_LEN_ADJUST__LEN_ADJUST = 0
#define CHIP_CONFIG_INPUT_PKT_PKT_LEN_ADJUST__LEN_ADJUST 0
// Pkt.PKT_LEN__ENDIAN = true
#define CHIP_CONFIG_INPUT_PKT_PKT_LEN__ENDIAN TRUE
// Pkt.PKT_LEN__IN_FIFO = true
#define CHIP_CONFIG_INPUT_PKT_PKT_LEN__IN_FIFO TRUE
// Pkt.PKT_CONFIG2__CRC_PADDING = false
#define CHIP_CONFIG_INPUT_PKT_PKT_CONFIG2__CRC_PADDING FALSE
// Pkt.PKT_WHT_BIT_NUM__PN_DIRECTION = 1
#define CHIP_CONFIG_INPUT_PKT_PKT_WHT_BIT_NUM__PN_DIRECTION 1
// Pkt.PKT_WHT_SEED__WHT_SEED = -1
#define CHIP_CONFIG_INPUT_PKT_PKT_WHT_SEED__WHT_SEED -1
// Sync.SYNC_BITS__BITS = -1272250368
#define CHIP_CONFIG_INPUT_SYNC_SYNC_BITS__BITS -1272250368
// Sync.SYNC_CONFIG2__LENGTH_SUB = 0
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG2__LENGTH_SUB 0
// Sync.SYNC_CONFIG2__SYNC_ERROR_ONLY_BEGIN = 0
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG2__SYNC_ERROR_ONLY_BEGIN 0
// Sync.SYNC_CONFIG__LENGTH = 1
#define CHIP_CONFIG_INPUT_SYNC_SYNC_CONFIG__LENGTH 1
// Match.MATCH_CTRL_1__MATCH_EN = 0
#define CHIP_CONFIG_INPUT_MATCH_MATCH_CTRL_1__MATCH_EN 0
// Global.GLOBAL_WUT_CONFIG__WUT_EN = 1
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_WUT_CONFIG__WUT_EN 1
// Global.GLOBAL_WUT_CONFIG__WUT_LBD_EN = 1
#define CHIP_CONFIG_INPUT_GLOBAL_GLOBAL_WUT_CONFIG__WUT_LBD_EN 1
// PowerAmplifier.PA_MODE__PA_MODE = 0
#define CHIP_CONFIG_INPUT_POWERAMPLIFIER_PA_MODE__PA_MODE 0
// PowerAmplifier.PA_BIAS_CLKDUTY__OB = 12
#define CHIP_CONFIG_INPUT_POWERAMPLIFIER_PA_BIAS_CLKDUTY__OB 12
// PowerAmplifier.PA_BIAS_CLKDUTY__CLK_DUTY = 0
#define CHIP_CONFIG_INPUT_POWERAMPLIFIER_PA_BIAS_CLKDUTY__CLK_DUTY 0
// Modem.API_TC = 29
#define CHIP_CONFIG_INPUT_MODEM_API_TC 29
// PowerAmplifier.PA_PWR_LVL__DDAC = 127
#define CHIP_CONFIG_INPUT_POWERAMPLIFIER_PA_PWR_LVL__DDAC 127
// PowerAmplifier.PA_MODE__EXT_PA_RAMP = false
#define CHIP_CONFIG_INPUT_POWERAMPLIFIER_PA_MODE__EXT_PA_RAMP FALSE
// BandwidthTime.value = 0.5
#define CHIP_CONFIG_INPUT_BANDWIDTHTIME_VALUE 0.5
// Modem.API_dsource = 0
#define CHIP_CONFIG_INPUT_MODEM_API_DSOURCE 0
// Modem.API_modulation_type = 3
#define CHIP_CONFIG_INPUT_MODEM_API_MODULATION_TYPE 3
#endif // __SLAB_RADIO_USER_INPUT__


//        _  _                          
//       | )/ )         Wireless        
//    \\ |//,' __       Application     
//    (")(_)-"()))=-    Software        
//       (\\            Platform        
