
// This file has been generated by the GUI designer. Do not modify.
namespace uploader
{
	public partial class Monitor
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget uploader.Monitor
			this.Name = "uploader.Monitor";
			this.Title = global::Mono.Unix.Catalog.GetString ("Monitor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
